### ISSUE TITLE
How to deploy?

### ISSUE THREAD

**Issue by MatyasKriz** [lyarenei/errbot-czechia-covid#1]
I've read the `README.md` thoroughly, but I'm at a loss as to how this is deployed into the real world? Could you please help me out on this one?

**Comment by lyarenei** [comment]
Hi, sorry for the delayed answer, I didn't even notice I've an issue opened here!

I've added an installation section to readme: https://github.com/lyarenei/errbot-czechia-covid#installation
Please read it and let me know if you have any other questions.

If not, then feel free to close this issue.

**Comment by MatyasKriz** [comment]
Yeah, I think I get it, thanks!
